const products = [
  {
    _id: '1',
    brand: 'Bridgestone',
    category: 'Tires',
    countInStock: 10,
    description: 'Bridgestone tire blizzak',
    image: '/images/bridgestone-blizzak.png',
    name: 'Bridgestone Blizzak',
    numReviews: 12,
    price: 89.99,
    rating: 4.5,
  },
  {
    _id: '2',
    brand: 'Firestone',
    category: 'Tires',
    countInStock: 7,
    description: 'Firestone Winter tires',
    image: '/images/firestone-winterforce.png',
    name: 'Firestone Winter Force',
    numReviews: 8,
    price: 599.99,
    rating: 4.0,
  },
  {
    _id: '3',
    brand: 'Goodyear',
    category: 'Tires',
    countInStock: 5,
    description: 'Goodyear Winter Tires',
    image: '/images/goodyear-wintercommand.png',
    name: 'Goodyear Winter Command',
    numReviews: 12,
    price: 929.99,
    rating: 3,
  },
  {
    _id: '4',
    brand: 'Michelin',
    category: 'Tires',
    countInStock: 11,
    description: 'Michelin defender tire',
    image: '/images/michelin-defender2.png',
    name: 'Michelin Defender 2',
    numReviews: 12,
    price: 399.99,
    rating: 5,
  },
  {
    _id: '5',
    brand: 'Michelin',
    category: 'Tires',
    countInStock: 7,
    description: 'Michelin X Ice tire',
    image: '/images/michelin-xice.png',
    name: 'Michelin X Ice',
    numReviews: 10,
    price: 49.99,
    rating: 3.5,
  },
  {
    _id: '6',
    brand: 'Motomaster',
    category: 'Tires',
    countInStock: 0,
    description: 'Motomaster tires',
    image: '/images/motomaster-winteredge.png',
    name: 'Motomaster Winteredge',
    numReviews: 12,
    price: 29.99,
    rating: 4,
  },
];

export default products;
